[project]
name = "reno-arxiv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.68.0",
    "arxiv>=2.2.0",
    "loguru>=0.7.3",
    "openai>=1.108.1",
]
